package DAL;
// Generated Dec 3, 2014 4:21:25 PM by Hibernate Tools 4.3.1



/**
 * TblDocenten generated by hbm2java
 */
public class TblDocenten  implements java.io.Serializable {


     private Integer id;
     private int cursistId;
     private String cursist;
     private String module;
     private String email;

    public TblDocenten() {
    }

    public TblDocenten(int cursistId, String cursist, String module, String email) {
       this.cursistId = cursistId;
       this.cursist = cursist;
       this.module = module;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getCursistId() {
        return this.cursistId;
    }
    
    public void setCursistId(int cursistId) {
        this.cursistId = cursistId;
    }
    public String getCursist() {
        return this.cursist;
    }
    
    public void setCursist(String cursist) {
        this.cursist = cursist;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


