package DAL;
// Generated Dec 3, 2014 4:21:25 PM by Hibernate Tools 4.3.1



/**
 * TblLokalen generated by hbm2java
 */
public class TblLokalen  implements java.io.Serializable {


     private Integer id;
     private int lokaalId;
     private int capaciteit;

    public TblLokalen() {
    }

    public TblLokalen(int lokaalId, int capaciteit) {
       this.lokaalId = lokaalId;
       this.capaciteit = capaciteit;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getLokaalId() {
        return this.lokaalId;
    }
    
    public void setLokaalId(int lokaalId) {
        this.lokaalId = lokaalId;
    }
    public int getCapaciteit() {
        return this.capaciteit;
    }
    
    public void setCapaciteit(int capaciteit) {
        this.capaciteit = capaciteit;
    }




}


