package DAL;
// Generated Dec 3, 2014 4:21:25 PM by Hibernate Tools 4.3.1



/**
 * TblModulen generated by hbm2java
 */
public class TblModulen  implements java.io.Serializable {


     private Integer id;
     private int moduleId;
     private String module;
     private String beschrijving;

    public TblModulen() {
    }

    public TblModulen(int moduleId, String module, String beschrijving) {
       this.moduleId = moduleId;
       this.module = module;
       this.beschrijving = beschrijving;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(int moduleId) {
        this.moduleId = moduleId;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public String getBeschrijving() {
        return this.beschrijving;
    }
    
    public void setBeschrijving(String beschrijving) {
        this.beschrijving = beschrijving;
    }




}


